---
- name: "Find content view versions of {{ satellite_cv.name }}"
  redhat.satellite.resource_info:
    server_url: "{{ satellite_server_url | default(omit) }}"
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    organization: "{{ satellite_organization }}"
    resource: content_view_versions
    params:
      content_view_id: "{{ satellite_cv.id }}"
  register: __satellite_versions

- name: "Delete unused content view versions of {{ satellite_cv.name }}"
  ansible.builtin.include_tasks: delete_cv_versions.yml
  vars:
    satellite_cv_name: "{{ satellite_cv.name }}"
    satellite_cv_versions: "{{ (__satellite_versions.resources | rejectattr('environments') | rejectattr('composite_content_view_ids') |
      rejectattr('published_in_composite_content_view_ids') | map(attribute='version') | map('float') | sort |
      map('string') | reverse | list)[satellite_content_view_version_cleanup_keep:] }}"
