---
- name: "Verify satellite_content_view_version_cleanup_keep is set"
  ansible.builtin.assert:
    that:
      - satellite_content_view_version_cleanup_keep|int >= 0
    fail_msg: "satellite_content_view_version_cleanup_keep needs to be set to >= 0"

- name: "Find all content views"
  redhat.satellite.resource_info:
    server_url: "{{ satellite_server_url | default(omit) }}"
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    organization: "{{ satellite_organization }}"
    resource: content_views
    search: "{{ satellite_content_view_version_cleanup_search | default(omit) }}"
  register: __satellite_all_cvs

- name: "Delete unused composite content view versions"
  ansible.builtin.include_tasks: delete_cv_versions.yml
  vars:
    satellite_cv_name: "{{ __satellite_ccv.name }}"
    satellite_cv_versions: "{{ (__satellite_ccv.versions | rejectattr('environment_ids') | map(attribute='version') | map('float') | sort
      | map('string') | reverse | list)[satellite_content_view_version_cleanup_keep:] }}"
  loop: "{{ __satellite_all_cvs.resources | selectattr('composite') | list }}"
  loop_control:
    label: "{{ __satellite_ccv.label }}"
    loop_var: "__satellite_ccv"
  when: (__satellite_ccv.versions | rejectattr('environment_ids') | map(attribute='version') | reverse | list)[satellite_content_view_version_cleanup_keep:]

- name: "Find and delete unused content view versions"
  ansible.builtin.include_tasks: find_and_delete_unused_cv_versions.yml
  loop: "{{ __satellite_all_cvs.resources | rejectattr('composite') | list }}"
  loop_control:
    label: "{{ satellite_cv.label }}"
    loop_var: "satellite_cv"
  when: (satellite_cv.versions | rejectattr('environment_ids') | map(attribute='version') | reverse | list)[satellite_content_view_version_cleanup_keep:]
