---
- name: Deploy SELinux Policies
  hosts: 74.235.186.212
  become: yes
  tasks:
    - name: Install SELinux policy package
      yum:
        name: selinux-policy-targeted
        state: latest

    - name: Set SELinux to enforcing mode
      selinux:
        policy: targeted
        state: enforcing

    - name: Reboot server to apply SELinux changes
      reboot:
        reboot_timeout: 300
      when: ansible_selinux.state != 'enforcing'

  handlers:
    - name: wait for server to come back online
      wait_for_connection:
        timeout: 300

  #   - include_role:
  #       name: acl_manager
  #       tasks_from: block_ip
  #     vars:
  #       source_ip: 172.17.13.98
  #       destination_ip: 192.168.0.10
  #       ansible_network_os: checkpoint



  # vars:
  #   ids_provider: snort

  # tasks:
  #   -  name: Add snort password attack rule
  #      include_role:
  #        name: "ansible_security.ids_rule"
  #      vars:
  #        ids_rule: 'alert tcp any any -> any any (msg:"Attempted /etc/passwd Attack"; uricontent:"/etc/passwd"; classtype:attempted-user; sid:99000004; priority:1; rev:1;)'
  #        ids_rules_file: '/etc/snort/rules/local.rules'
  #        ids_rule_state: present



