- hosts: localhost
  roles:
    - role: redhat.satellite.convert2rhel
      vars:
        satellite_server_url: "https://satellite.example.com"
        satellite_username: "{{ username }}"
        satellite_password: "{{ password }}"
        satellite_organization: "Default Organization"
        satellite_manifest_path: "./convert2rhel.zip"
        # satellite_content_rhel_enable_rhel7: true
        satellite_content_rhel_enable_rhel8: true
        satellite_content_rhel_rhel8_releasever: 8.7
        satellite_content_rhel_wait_for_syncs: false
        satellite_convert2rhel_lifecycle_env: "Library"
        satellite_convert2rhel_content_view: "Default Organization View"
        # satellite_convert2rhel_enable_oracle7: true